// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

using System.ComponentModel.DataAnnotations.Schema;

namespace Contoso.FraudProtection.ApplicationCore.Entities.BasketAggregate
{
    public class BasketItem : BaseEntity
    {
        [Column(TypeName = "Money")]
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public int CatalogItemId { get; set; }

        #region Autogenerated by Visual Studio
        public override bool Equals(object obj)
        {
            var item = obj as BasketItem;
            return item != null &&
                   CatalogItemId == item.CatalogItemId;
        }

        public override int GetHashCode()
        {
            return 456376666 + CatalogItemId.GetHashCode();
        }
        #endregion
    }
}
